server:
  port: 7999
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: ADMIN-SERVER
          uri: lb://admin-server
          predicates:
            - Path=/admin/**
      filters:
        - SwaggerHeaderFilter